### ISSUE TITLE
Wishlist Features

### ISSUE THREAD

**Issue by Polymega** [pmttavara/ph2#1]
Hi Phillip,

Thank you for everything you're doing. If you don't mind, I'd like to list some wishlist features for the tool. If any of the things below are not feasible or you just don't want to bother, feel free to tell me to hush. Really, the most important things in the list below are the import/export functions.

---------------------------

### Display Modes
Have a feature in imgui to toggle between:

- [x] #2
- [x] #3

Have checkboxes for the following, which can be enabled in any combination with each other to work alongside the display modes mentioned above:

- [x] #4
- [x] #5

I'm ignorant to what type of workflow would be involved here, so apologies if this is outlandish to ask about.

-----------------------------

### File Directory/Changer

I know the tool is still in its early prototype stage, and you may have had something like this already planned, but perhaps have the ability to select a folder for the tool to search its directory for any cld/map files and then have a way to cycle between found cld/map files?

This isn't critical to have, but would be a nice convenience feature.

-----------------------------

### Import/Export Functionality

I'd like to know your thoughts on how best this could be done. 

OBJs can hold mesh grouping information, but Maya, Unity, Blender, and 3ds Max may read and save out these groups in different ways. I'm not sure. If they do all read/save mesh groups differently, then it would be a pain to try and make this work across the many 3D editing software out there. You could make it work for one specific piece of 3D software, but that's also limiting for different reasons.

 So how could you successfully import/export geometry data via geometry ID through a map file? Here's my idea:

In your tool, you've implemented checkboxes to show/hide mesh IDs. Have it to where **only one** mesh ID can be checked in order for an **export/import** button to become clickable. This way, the end user has to specifically choose what mesh group/ID they want to export/import for changes.

There is likely a more elegant way to handle this, and it's safe to say I'm probably overlooking several things here, which is why I wanted to discuss it out loud with you. But that's the initial idea I had. This would prevent worry of importing whole-level edited OBJs back into the tool; the worry here being whether or not the 3D editing software retained correct mesh ID information on OBJ export for your tool to read and understand when importing back in.

I suppose having an "export entire map" feature may also be good? Perhaps it gives a warning that importing OBJs should only be done on a per-mesh ID basis? An Export All feature may also be nice because some people may just want to export the whole map to use elsewhere outside of the game.

------------------------------

Thanks for letting me think out loud here. Looking forward to your thoughts on some of these things; I always enjoy brainstorming!

**Comment by pmttavara** [comment]
Thank you for making these recommendations, I'll implement all of them. I'll also add support file drag-and-drop as an alternative to file-browsing, in case that isn't easy to support in the web-browser version of the program that I'm hoping to do later.

I haven't progressed to the point where I'm able to speak with any confidence about what should be done with mapmesh IDs. At this point, I'm deferring completely to what you've written here, and I'm sorry that I can't give you any feedback on whether it's a good or bad idea (other than that it would be pretty unfortunate, if practical, to have to export to individual mapmeshes/groups as separate model files or merge them together in way that is lossy with information). I'll look into it more once I start working on factoring map loading into a library, or when I start implementing import/export, whichever comes first.

I'm really really sorry about the ridiculously late reply, I've never been the owner of a repo that's had an issue before :) I'll start checking this sort of thing regularly, so I'll be faster to respond from now on.

**Comment by Polymega** [comment]
❤️
