### ISSUE TITLE
Request: Remember set BG color

### ISSUE THREAD

**Issue by Polymega** [pmttavara/ph2#10]
Whenever you close/relaunch the tool, the BG color you set will reset. Likewise, when loading a new .map file, the BG color will also reset.

May I request a feature to save the BG color to the INI and have the tool launch with the last BG color used and also retain this color on various loaded .map files while using the tool?

And perhaps include a "Reset BG" button around it that'll change it back to the dark grey you have it auto-set to?

**Comment by pmttavara** [comment]
af3f903 `Editor: Remember set BG color (#10)`
