### ISSUE TITLE
Retain camera position when importing OBJ model

### ISSUE THREAD

**Issue by Polymega** [pmttavara/ph2#11]
Currently, when you import an OBJ model, it moves the camera upon import. I believe it's moving and centering the camera to the new geometry that was imported, but I'm unsure.

May I ask if the camera can stay where it's at upon OBJ import? As currently, it can be a little disorienting to re-find your position once the camera jumps on its own.

**Comment by pmttavara** [comment]
This is easy, will do!

**Comment by pmttavara** [comment]
d9270f3 `Retain camera position when importing OBJ model (#11)`
