### ISSUE TITLE
Early Testing Report

### ISSUE THREAD

**Issue by Polymega** [pmttavara/ph2#6]
Hi Phillip,

Please forgive me, but the anticipation proved too much and I wanted try out the tool and get my toes wet. To start: This... Is... Amazing!! I feel like a kid in a candy shop playing with this. I've had either a smile or grin on my face the past few hours using your tool. This is wonderful and it still feels like a dream to me. 😭 

As I was playing around with it, I came across a few quirks I'd like to report your way, if that's okay.

# Exporting

When exporting geometry or individual, specific textures, you _must_ type in ".obj" or ".dds" as part of the filename, otherwise it'll save without the extension. This also makes the material file for the OBJ saved out as "*.obj.mtl" when you have to manually type in the extension for the OBJ filename.

----------------------

Textures are not exporting correctly. Files are being created, but there's no data in them.

![image](https://github.com/pmttavara/ph2/assets/27395260/e5062130-7896-4cde-b5fe-6f25016dfb5d)

---------------------

When exporting geometry, if you choose to flip it on the axis, it'll incorrectly reverse the normals as part of the export.

### Export as-is (backface culling enabled)

![image](https://github.com/pmttavara/ph2/assets/27395260/af03439f-0949-49e1-8b77-e45d926a01f0)

### Export with flipped axis (backface culling enabled)

![image](https://github.com/pmttavara/ph2/assets/27395260/ffdaf4f3-cda3-424f-abef-90d73ae89bdf)

---------------------

I'm experimenting with another plug-in for Maya to import the OBJ and it kept freezing the software on import. Through experimentation I've found it's due to this line that's at the end of the .mtl file when exported through the tool:

```
  map_d -imfchan m E:\Silent Hill\PC SH2 Enhanced Edition WORK\Game File Adjustments\MAP Edits\scenes\bg\th\test3.tex_6116.dds
```

When searching for the `map_d` line, it looks like it might be a Blender-specific line for OBJs? Is it imperative to keep this line for export or would it be okay to have it removed?

-------------------

I've found out why Maya wasn't importing materials upon OBJ import... and it's a remarkably dumb reason: The filepaths need to be relative. For example, this won't work for the OBJ:

```
mtllib E:\Silent Hill\PC SH2 Enhanced Edition WORK\Game File Adjustments\MAP Edits\scenes\bg\th\teeesssttt.mtl
```

...but this will:

```
mtllib teeesssttt.mtl
```

Same with the .mtl file. From this:

```
  map_Kd E:\Silent Hill\PC SH2 Enhanced Edition WORK\Game File Adjustments\MAP Edits\scenes\bg\th\teeesssttt.tex_6118.dds
```

...to this: 

```
  map_Kd teeesssttt.tex_6118.dds
```

So can either the filepaths within the .obj and .mtl be made relative to each other, or could you make this a checkable option upon export?

-------------------

That's all I found so far! If anything else comes up I'll leave it as a comment on this ticket.

I'm absolutely in love with this tool, Phillip. 😍 😍 😍

**Comment by Polymega** [comment]
Apologies, a few others I forgot to write down.

# UI

When first launching the tool (aka a blank slate), pressing the **Save MAP** option will immediately close down the tool.

----------------

When first launching the tool, if nothing has been touched with the tool yet and you go to **Open...** it'll warn you that there's unsaved changes.

----------------

A total lazy/convenience thing: Is it possible for the tool to remember the last directory path used for navigating files (the window that comes up for exporting/importing/saving/etc) upon closing/relaunching the tool? Right now, it defaults to your Documents folder upon each relaunch.

**Comment by Polymega** [comment]
# Import

When exporting an OBJ out of Maya, it does not import back into the tool while retaining separate Mesh Part Groups. It instead imports it all under a single mesh group. 

May I ask you to broaden the tool's importability with this? Below are the differences in how the tool (`tool_export.obj`) and Maya (`maya_export.obj`) are handling mesh groups on OBJ export:

![image](https://github.com/pmttavara/ph2/assets/27395260/f19abc2e-dcb3-487f-a735-015d9b1fe4e7)

Here are the files if you want to take a direct look at them: [exports.zip](https://github.com/pmttavara/ph2/files/11657530/exports.zip)

**Comment by pmttavara** [comment]
Thank you so much for this thorough usage test and report. It's really helpful to have a detailed list of what's problematic and what needs fixing.

I've made some recent changes to address some of these items:

- c68bad0 Don't treat empty maps as having unsaved changes
- c68bad0 Prevent "Save MAP" from crashing after startup
- b696ad0 Move camera to the center of map when you hit "Reset Camera", not just when you load the .map
- 737b86f OBJ export: Auto-append .obj to filename; replace .obj with .mtl for MTL file
- 68a9086 OBJ export: Remove "master_group1:" and shorten group names
- aaa81e9 OBJ export: Use relative file paths in OBJs/MTLs
- 9fc6f4d OBJ export: Add option to omit "map_d -imfchan m" in MTL export
- 60229ff OBJ export: Write material into group name
- 51a6a71 Save settings to a file (settings.ph2)

I also went ahead and added some usability features:

- d3bd9b2 Make shift-clicking empty space NOT deselect anything
- e83f0ff In fullscreen mode, show only the viewport window and expand it to the full screen
- 82bc090 When you try to exit while there are unsaved changes, prompt to save changes
- 6b82db2 Allow click to select while in orbiting/flycam mode
- 6b82db2 Allow holding Shift to hide vertex drag widgets

And other bugfixes:

- 8c07b3d Don't drag/mouselook when clicking a window that blocks the viewport
- 3e69465 Prevent Shift-scroll in viewport
- 9976922 Fix camera-reset not working when the edit widget is closed
- b4c6d01 Disable importing into an empty map
- e64c2c1 Disable "New Material" on empty maps

If I've read your report right, there should about be 3 major tasks left:

- Why are there no textures???
- At least a way to highlight/identify the hovered Mesh Part Group
- OBJ import: Split OBJs into mesh part groups based on the OBJ's mesh part groups, not just materials; and preserve materials even with tools that don't support them by encoding materials into group names

Please feel free to take another look at the tool when you have some time, and let me know if you find items to go through.
Unfortunately I still don't have an official binary release available, but here's an off-the-cuff build, so you don't have to compile it yourself:
[ph2ed_proto_e64c2c1_2023-06-26_0854.zip](https://github.com/pmttavara/ph2/files/11869113/ph2ed_proto_e64c2c1_2023-06-26_0854.zip)

(I wasn't expecting anybody to build the tool yet 😃 )

Thanks again, and hope this helps!

**Comment by Polymega** [comment]
> If I've read your report right, there should about be 3 major tasks left:

Those look to be correct. In addition to those tasks, there is also the following:

----------

When exporting individual, specific textures (through the `Textures` tab), you _must_ type in ".dds" as part of the filename, otherwise it'll save without the extension.

--------------

I believe this is a typo? Should say "Flip X on ~~import~~ export" ?

![image](https://github.com/pmttavara/ph2/assets/27395260/09a6fb91-af72-40a8-8971-d1326ccd46de)

----------

When exporting geometry, if you choose to flip it on its axis, it'll also reverse the normals as part of the export. ([See this post.](https://github.com/pmttavara/ph2/issues/6#issue-1740063330))

We ideally don't want the normals flipped with everything else because, when working with the file, all the normals are then reversed. Is it possible to _not_ flip the normals when opting to flip the mesh over?

If there are too many variables at play to do this--depending on whether a user has opted to flip only on X, Y, _or_ Z--would it help to remove the X, Y, and Z options and just have just _one_ checkbox that says something like "Flip geometry" which flips it on X, Y, _and_ Z? If desired/needed, a tooltip could be included explaining why this option exists. Anyway, by having only one check box for flipping, it should hopefully make managing normal direction a lot easier to predict.

Perhaps on import/export, you can have a "sub checkbox" (like what's seen for "Alpha Channel Texture References" above). Something like:

**For both Export/Import:**
- [X] Flip geometry
    - [X] Reverse normals

------------

This might be a non-issue, but I wanted to share this with you ahead of time just in case.

_I exported the _entirety_ of `th09.map` for the examples below._

**Here is the group order with how your tool exports the geometry:**

![image](https://github.com/pmttavara/ph2/assets/27395260/8f4adbcf-c6fc-4d7f-81fc-8bd50becc503)

**Here is the group order when I import the tool's OBJ through the Maya plugin that retains vertex color information (which is what I will be using):**

![image](https://github.com/pmttavara/ph2/assets/27395260/0dea0246-99f0-4fa9-b02b-6d8bc5b116cd)

^ Notice the order of the groups is jumbled up compared to the order in which your tool exported them. Also notice your master group `PH2Grp` was "merged" into each mesh group's name (as `PH2Grp_blah_blah`). And where is this new `th09` group name coming from? When it's imported into Maya, all of the mesh groups are placed under a master group using the filename of the .obj (in this case, "th09.obj"). See highlighted part above.

Maybe, at least for Maya, it's better for the tool to _not_ place everything under a master group? Or have an option for this in the tool on export? Just note that, no matter what, Maya _itself_ will place everything under its own master group using the filename of the OBJ as the master group's name. Maya is a bit dumb/archaic when it comes to OBJs......

**Anyway, here are those groups when I export the Maya OBJ through the Maya plugin that retains vertex color information (which is what I will be using):**

![image](https://github.com/pmttavara/ph2/assets/27395260/7cadf94f-c251-41ff-80da-24bd7993d8c9)

I don't know if, at all, this will affect importing back into the tool, but I wanted to make you aware that Maya imports the mesh groups under its own master group (which will stay retained on export, by default) and the vertex color plugin for Maya can change the ordering of the groups.

------------

...I believe that's all I got! Thank you!!!

PS -  

> TODO: OBJ import: Split OBJs into mesh part groups based on the OBJ's mesh part groups, not just materials; and preserve materials even with tools that don't support them by encoding materials into group names

Nice thinking for this solution!

PSS - And adding a crosshair to the viewport when moving the camera was a slick touch. 😎
PSSS - Look at you adding F11 and Alt + Enter to toggle fullscreen mode! You probably did this a while back but I'm just now discovering it. Nice!

**Comment by Polymega** [comment]
Just to show how stupid Maya can be:

Refer to my post directly above where I wrote:

> Anyway, here are those groups when I export the Maya OBJ through the Maya plugin that retains vertex color information (which is what I will be using):

Here is what _that_ looks like if I import back into Maya again:

![image](https://github.com/pmttavara/ph2/assets/27395260/76942c9b-8090-4f0b-b802-c4f2d1d206e8)

So every time you re-import an OBJ back into Maya, it makes a _new_ master group using the filename of the OBJ and "merges" the _old_ master group name as part of the mesh group name. So if you imported/exported the same OBJ four different times in Maya, it would look something like:

- NewMasterGroupName
   - OldMasterGroupName_OlderMasterGroupName_OldestMasterGroupName_Blah_Blah_1
   - OldMasterGroupName_OlderMasterGroupName_OldestMasterGroupName_Blah_Blah_2
   - OldMasterGroupName_OlderMasterGroupName_OldestMasterGroupName_Blah_Blah_3
   - ...

**Comment by pmttavara** [comment]
Changes to address these items:

- 7a03ad4 Fix DDS files not getting exported in release. Whoops!
- 7a03ad4 Auto-append .MAP, .OBJ, and .DDS via dialog box instead of custom code
- 1d2f620 Fix typo
- 83393a9 Option to invert face winding on import/export

Other changes:

- a9378fd 745f785 4db11b4 fc7a7c2 Continuous integration with automatic releases
- 233f785 3b32d18 Automatic crash reporter (sends anonymous crash report to a private Discord channel)
- 233f785 Deterministic builds
- 0abee86 Increase bounds on buffer geometry size
- 29261cd Fix DDS import not checking OBJ-relative paths

Remaining major tasks:

- At least a way to highlight/identify the hovered Mesh Part Group
- OBJ import: Split OBJs into mesh part groups based on the OBJ's mesh part groups, not just materials; and preserve materials even with tools that don't support them by encoding materials into group names

**Comment by pmttavara** [comment]
Change to address these items:

- e52a015 Solo-highlight the hovered mesh part group

Remaining major task:

- OBJ import: Split OBJs into mesh part groups based on the OBJ's mesh part groups, not just materials; and preserve materials even with tools that don't support them by encoding materials into group names

This new highlight change isn't super ideal UX, but it should do as a basic implementation. Hopefully I'll be able to return to it later when I have some time.

**Comment by pmttavara** [comment]
Change to address the remaining item:

- df8ef87 Preserve mesh part grouping in OBJ import

There's certain to be some bugs in this change because it's pretty big, so just submit them as they come in. I'll be automatically receiving the crash reports whenever the program crashes.

**Comment by Polymega** [comment]
Thank you thank you, Phillip. I'll close this ticket as notes/issues mentioned have been addressed. In the future, I'll open tickets for other issues that crop up.
